name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: '55 14 * * 3'

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
    - name: Send CURL
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"content": "Dzisiaj środa"}' ${{ secrets.NEWBIES_DISCORD_WEBHOOK }}
